# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ct_algorithm
#' @title Factor Analysis by Correlation Thresholding
#' 
#' @description Generates a set of factor analysis structures by thresholding
#' the correlation graph at a sequence of points.
#'
#' @param R; numeric matrix of correlations.
#' @param tau; optional numeric vector of threshold \eqn{\tau} values.
#' @param k; optional numeric scalar integer indicating minimum clique size
#' to search for. Must be 2 or greater, default is 2.
#' 
#' @details If `tau` is not given, then a set is automatically generated as
#' follows:
#' \itemize{
#'   \item If the number of observed variables is \eqn{\leq 10}, then every
#'   possible threshold is checked. This is at most 45 thresholds.
#'   \item If the number of observed variables is \eqn{> 10}, then 50
#'   evenly spaced thresholds are generated from the interval \eqn{[0, 1]}.
#' }
#' Prior to clique analysis, redundant \eqn{\tau} values are removed for
#' computational efficiency. Therefore, if two \eqn{\tau} values result in
#' identical factor analysis structures, the structure will only be returned
#' once.
#' 
#' @return `list` of `numeric matrix`; each contains the support of the
#' coefficients or support of the factor loadings: \eqn{\mathcal{A}(\Lambda)}.
#' One per (non-redundant) threshold \eqn{\tau}.
#' 
#' @references Kim, D. S., & Zhou, Q. (2023). Structure learning of latent
#' factors via clique search on correlation thresholded graphs. *Proceedings
#' of the 40th International Conference on Machine Learning., 202*,
#' 16978–16996. \url{https://proceedings.mlr.press/v202/kim23aa.html}
#' 
#' @export
NULL

ct_algorithm <- function(R, tau = NULL, k = 2L) {
    .Call(`_fact_ct_algorithm`, R, tau, k)
}

#' @name ct_structure
#' @title Correlation Thresholded Factor Analysis Structure
#' 
#' @description Generates a factor analysis structure through correlation
#' thresholding.
#'
#' @param R; numeric matrix of correlations.
#' @param tau; numeric scalar of threshold \eqn{\tau} value.
#' @param k; optional numeric scalar integer indicating minimum clique size
#' to search for. Must be 2 or greater, default is 2.
#' @param check; optional logical scalar to indicate if `R` should be
#' checked to be a valid input.
#' 
#' @return `numeric matrix` of the support of the coefficients or support of
#' the factor loadings: \eqn{\mathcal{A}(\Lambda)}.
#' 
#' @references Kim, D. S., & Zhou, Q. (2023). Structure learning of latent
#' factors via clique search on correlation thresholded graphs. *Proceedings
#' of the 40th International Conference on Machine Learning., 202*,
#' 16978–16996. \url{https://proceedings.mlr.press/v202/kim23aa.html}
#' 
#' @export
NULL

ct_structure <- function(R, tau, k = 2L, check = TRUE) {
    .Call(`_fact_ct_structure`, R, tau, k, check)
}

#' @name pare_tau
#' @title Pare Tau
#' 
#' @description Removes redundant \eqn{\tau} values given a correlation matrix
#' \eqn{R}.
#'
#' @param R; numeric matrix of correlations.
#' @param tau; numeric vector of \eqn{\tau} values.
#' 
#' @details Two \eqn{\tau} values are considered redundant if they result in
#' the same thresholded graph. Redundant \eqn{\tau} are removed prior to
#' clique analysis for efficient computation.
#' 
#' @return `numeric vector` of original \eqn{\tau} values with
#' redundant elements removed.
#' 
#' @export
NULL

pare_tau <- function(R, tau) {
    .Call(`_fact_pare_tau`, R, tau)
}

